---
title: ""
toc: true
number-sections: true
lang: en
---


## Book

* Schneedorf, J.M. [Bringing Content to Life in Basic Education: Molecules, Graphs, and Interactive Maps](https://www.pimentacultural.com/livro/vivificando-conteudos/). Pimenta Cultural Publishing, 132 p., 2025. ISBN 978-85-7221-397-4.

* Schneedorf, J.M. *Codes for Content: Dynamic Documents for Research and Teaching with R & RStudio*. UNIFAL-MG Press, Alfenas, 342 p. (in press).

* Schneedorf, J.M., Silva, L.E., Mafra, L.A.S. (Eds.). [Open Educational Resources: Sharing Experiences at the Federal University of Alfenas](http://dx.doi.org/10.31560/pimentacultural/978-85-7221-396-7). 1st ed. São Paulo: Pimenta Cultural, 2025. Vol. 1. 112 p.

* Schneedorf, J.M., Silva, L.E., Mafra, L.A.S. (Eds.). [Unifal Interactive: Digital Education Projects at the Federal University of Alfenas](http://dx.doi.org/10.31560/pimentacultural/978-85-7221-395-0). 1st ed. São Paulo: Pimenta Cultural, 2025. Vol. 1. 91 p.

* Schneedorf, J.M., Rodrigues, K.L. [Basic Biochemistry: of Humans, Animals, and Plants](http://dx.doi.org/10.13140/RG.2.2.32623.55208). 353 p., 2024. ISBN: 978-65-00-90366-9.

* Schneedorf, J.M. [Quantitative Biochemistry](http://dx.doi.org/10.13140/RG.2.2.36090.40644) & R. 152 p., 2022. ISBN: 978-65-00-52125-2.

* Schneedorf, J.M. [SISMA – Dynamic Visualization in Catalysis & Metabolism](http://dx.doi.org/10.13140/RG.2.2.25027.92964). 95 p., 2022. ISBN: 978-65-00-52124-5.

* Schneedorf, J.M. [Structural Biochemistry: Guided by Jmol](http://dx.doi.org/10.13140/RG.2.2.29268.10882). 140 p., 2019. ISBN 978-85-63-47342-4. UNIFAL-MG.

---

## Book Chapter

* Schneedorf, J.M. [Dynamic Documents in Reproducible Teaching with R & RStudio](http://dx.doi.org/10.47247/ASJ/6063.091.8). In: *Emerging Technologies in Education*. V & V Editora, Santo André (SP), 2026.

* Schneedorf, J.M. A practical tool in computational thinking and AI for creating and sharing interactive learning objects at your fingertips. In: *Restricted Use of Cell Phones in Schools — What Now?* V & V Editora, Santo André (SP), 2026 (in press).

* Schneedorf, J.M. An application for interactive and dynamic HTML browser graphics and a custom GPT for code generation. In: Sumariva, G. *Robotics, Innovation and Education: Connections for the Future*. V & V Editora, Santo André (SP), 2026 (in press).

* Schneedorf, J.M. [Reproducible Teaching as an Active Learning Methodology](http://dx.doi.org/10.47247/ASJ/6063.091.8). In: *Emerging Technologies in Education*. V & V Editora, Santo André (SP), 2026.

* Schneedorf, J.M. JSPlotly: an open application for interactive and dynamic graphics in science education. In: Gerolin, E., Crisafulli, U. *Teachers’ Talk: Challenges, Innovations and Practices in Science Teaching*. V & V Editora, Santo André (SP), 2026 (in press).

* Schneedorf, J.M., Rodrigues, B.S., Hornink, G.G. [OIER – Interactive Objects in Reproducible Education: an R-based approach](http://dx.doi.org/10.47247/ASJ/6063.091.8). In: *Emerging Technologies in Education*. V & V Editora, Santo André (SP), 2026.

* Schneedorf, J.M. A platform for simulation-based learning in Mathematics and Natural Sciences supported by AI. In: Silva, J.L., Alves, Araújo, F.G.A., Souza, L.A.S. *Exact Sciences: Dialogues Between Research and Practice*. V & V Editora, Santo André (SP), 2026 (in press).

* Silva, L.E., Lima, D.C., Isgrignero, I., França, J.G., Lage, R.M., Schneedorf, J.M., Mafra, L.A.S. [Tales Ludos: Enhancing User Experience in the Development of Online Educational Games](http://dx.doi.org/10.47247/ASJ/6063.091.8). In: *Emerging Technologies in Education*. V & V Editora, Santo André (SP), 2026.

* Schneedorf, J.M. R and RStudio: a platform for implementing reproducible teaching. In: *Active Learning: From Basic Education to Higher Education*. V & V Editora, Santo André (SP), 2026 (in press).

* Schneedorf, J.M. et al. Molecular Garden: a virtual catalog for reproducible teaching of atomic models in basic education. In: *Active Learning: From Basic Education to Higher Education*. V & V Editora, 2026 (in press).

* Schneedorf, J.M. R packages for creating active learning objects in reproducible teaching. In: *Active Learning*. V & V Editora, 2026 (in press).

* Schneedorf, J.M., Hornink, G.G. Development of Digital Competencies in Higher Education Through Project-Based Learning with R and RStudio. In: *Active Learning*. V & V Editora, 2026 (in press).

* Schneedorf, J.M. Prompt literacy in the production of interactive educational objects for reproducible teaching with R & RStudio. In: *Reflections and Reports on Artificial Intelligence*. V & V Editora, 2026 (in press).

---

## Article

* Schneedorf, J.M. Living books: a proposal for reproducible teaching with R & RStudio. *Revista Eletrônica Casa de Makunaima*. 2026 (in press).

* Schneedorf, J.M. [JSPlotly: an application for interactive graphics in Biochemistry for HTML viewers](https://www.bioquimica.org.br/index.php/REB/article/view/1111/866). *Journal of Biochemistry Education*, 23(1), 1–15, 2025.

* Schneedorf, J.M. HTML application for building and sharing AI-assisted interactive objects for teaching and research. ESUD/CIESUD Conference Proceedings, 2025.

* Schneedorf, J.M. Bioquanti: an interactive website for teaching and learning in Biochemistry. *Journal of Biochemistry Education*, 21(1), 110–124, 2023.

* Oliveira, G.A.V.; Schneedorf, J.M. A Simple, Fast and Portable Method for Electrochemical Detection of Adenine Released by Ricin Enzymatic Activity. *Toxins* 13 (2021): 238.

* Oliveira, G.A.V.; Schneedorf, J.M. An Electrochemical Approach to Follow and Evaluate the Kinetic Catalysis of Ricin on hsDNA. *Life* 11(5) (2021): 405.

---

## Patent

* Oliveira, G.A.V.; Schneedorf, J.M. Method for the Detection of Ricin and Characterization of Its Enzymatic Activity in Real Time by Electrochemistry. INPI, registration no. BR1020200206532, 2020.

---

## Software

* Macedo, J.A. et al. SISMA: Self-Catalytic Maps System. Computer Program. INPI registration no. 08869-3 (2008).

* Schneedorf, J.M. JSPlotly & GSPlotly: application and AI-based code generator for interactive HTML graphics (2025). Deposited at eduCAPES, registration no. 972869.

---

## Website

* Schneedorf, J.M. Bioquanti (2022). Deposited at eduCAPES, registration no. 748598.

---

## Custom GPT

- Schneedorf, J.M. [GSPlotly: interactive script generator for JSPlotly](https://chat.openai.com/g/g-6819fbb8d2d08191bf7d50a3dbeadb0d-gsplotly). Custom GPT. OpenAI, 2025. 

