# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pt:
  languageCode: pt-br
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/pt-br

# Uncomment the lines below to configure your website in a second language.
en:
  languageCode: en
  contentDir: content/en
  title: Quantitative Biochemistry
  params:
    description: Site description in English...
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Tools
        url: '#ferramentas'
        weight: 30
      - name: About
        url: '#contato'
        weight: 60



