# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

# Menu novo
main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Ferramentas
    identifier: ferr
    url: '#programas'
    weight: 20
  # - name: EM # nome que aparece à esquerda como um tópico
  #   parent: ferr # ítem pai 
  #   url: '#em'  # nome do arquivo na pasta menu ferramentas
  #   weight: 10
  # name: Programas
  # parent: ferr
  # url: '#programas'
  # weight: 20
  - name: Ensino Básico
    url: https://errre.netlify.app/
    weight: 40
  - name: Contato
    url: '#contato'
    weight: 60

###################################

# ############################# Menu velho
# main:
#   - name: Home
#     url: '#about'
#     weight: 10
#   # - name: Posts
#   #   url: '#posts'
#   #   weight: 20
#   - name: Ferramentas
#     url: '#ferramentas'
#     weight: 30
#   # - name: Talks
#   #   url: '#talks'
#   #   weight: 40
#   # - name: Publications
#   #   url: '#featured'
#   #   weight: 50
#   - name: Contato
#     url: '#contato'
#     weight: 6
    
#######################################


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70


