---
title: "Workshop - Funcionalidades diversas do JSPlotly e exemplos"
format: html
toc: true
number-sections: true
lang: pt
---



## [Barras](work/barras.html){target="_blank"}

## [Fluxograma de blocos](work/fluxogr_papas.html){target="_blank"}

## [Subplot](work/subplot2.html){target="_blank"}

## [Parábola 1 - slider e surgimento](work/parabola1.html){target="_blank"}

## [Parábola 2 - controles (sliders)](work/parabola2.html){target="_blank"}

## [Parábola 3 - Lançamento oblíquo](work/lancamento.html){target="_blank"}

## [Parábola 4 - Jogo de Arco e Flecha (botões)](work/arcoFlecha.html){target="_blank"}

## [Outra função - slider](work/funcao_slider.html){target="_blank"}

## [Menu](work/menu.html){target="_blank"}

## [Seletor](work/seletor.html){target="_blank"}

## [Menu & Seletor](work/literatObras.html){target="_blank"}

## [Menu & animação](work/cineticaRP.html){target="_blank"}

## [Mapa mundi](work/mapa.html){target="_blank"}

## [Mapa mundi com animação](work/mapaAnim.html){target="_blank"}

## [Mapa Brasil com animação - queimadas (fictício)](work/anim_queimad.html){target="_blank"}

## [Objeto 3D](work/3d.html){target="_blank"}

## [Superfície 3D](work/3d_superf.html){target="_blank"}

## [Painel (*dashboard*)](work/painel.html){target="_blank"}

## [Tábua de desenho](work/desenho.html){target="_blank"}

## [Espirógrafo animado](work/espirogr.html){target="_blank"}

## [Fractal de Mandelbrot](work/mandelbrot.html){target="_blank"}

## [Jogo da Vida de Conway](work/lifesgame.html){target="_blank"}

## [Curva de Gauss e área rachurada por p-valor](work/gauss.html){target="_blank"}

## [Pesquisa - Tabela](work/tabela.html){target="_blank"}

## [Pesquisa - Inserção de dados de usuário - CSV](work/dados_csv.html){target="_blank"}

## [Pesquisa - Análise de Variância e teste de Tukey-HSD](work/ANAVA_Tukey.html){target="_blank"}

## [Programação - Treinamento em JavaScript](work/treinamento_JS.html){target="_blank"}

## [Pesquisa - Regressão Linear - ajuste no script](work/regressLin.html){target="_blank"}

## [Animação - Histograma](work/anim_histogr.html){target="_blank"}

## [Animação - potencial de ação neuronal](work/anim_neuronio.html){target="_blank"}

## [Animação - Mini Sistema Solar](work/plan4_miniSistSol.html){target="_blank"}

## [Animação - Mini Sistema Solar 2 - dados aproximados](work/miniSistSol.html){target="_blank"}

## [Animação - Afélio e Periélio](work/afelio_perielio.html){target="_blank"}

## [Animação - Pêndulo](work/pendulo.html){target="_blank"}

## [Animação - Massa e Mola](work/massa_mola.html){target="_blank"}

## [Som - flauta doce (script)](work/flauta3.js){target="_blank"}

## [Som - piano (script)](work/piano.js){target="_blank"}

## [Game - Pong (script)](work/pong.js){target="_blank"}









