---
title: "Workshop - Funcionalidades do JSPlotly"
format: html
toc: true
number-sections: true
lang: pt
---



## Gráficos

### [Comuns (Biologia) ](work/barras.html){target="_blank"}

### [Múltiplos - com referência cruzada (Química)](work/subplot2.html){target="_blank"}

### [Gráficos tridimensionais (Física)](work/3d_superf.html){target="_blank"}

## [Mapas (Geografia)](work/mapa.html){target="_blank"}

## [Diagramas (Ensino Religioso)](work/fluxogr_papas.html){target="_blank"}

## [Objeto 3D (Artes)](work/3d.html){target="_blank"}

## [Desenho (Artes)](work/desenho.html){target="_blank"}

## Widgets (componentes de interatividade)

### Slider (deslizador)

#### [Visualização progressiva de equação](work/funcao_slider.html){target="_blank"}

#### [Ajustes de equação](work/parabola2.html){target="_blank"}

### Menu, seletor, e botões

#### [Menu (escolha de função](work/menu.html){target="_blank"}

#### [Seletor (tema genérico)](work/seletor.html){target="_blank"}

#### [Menu e seletor (Literatura)](work/literatObras.html){target="_blank"}

#### [Objetos complexos (Fractal)](work/mandelbrot.html){target="_blank"}

## Análise de dados (Pesquisa)

### [Tabela](work/tabela.html){target="_blank"}

### [Carregamento de dados - CSV](work/dados_csv.html){target="_blank"}

### [Curva de Gauss e p-valor (Estatística)](work/gauss.html){target="_blank"}

### [Análise de Variância e teste de Tukey-HSD](work/ANAVA_Tukey.html){target="_blank"}

### [Regressão Linear (ajuste no script)](work/regressLin.html){target="_blank"}

## [Treinamento em JavaScript (Programação)](work/treinamento_JS.html){target="_blank"}

## Animação

### [Lançamento oblíquo (Física)](work/lancamento.html){target="_blank"}

### [Mapa Mundi (Geografia, História)](work/mapaAnim.html){target="_blank"}

### [Mapa - Queimadas (C. da Natureza; dados fictícios)](work/anim_queimad.html){target="_blank"}

### [Menu e botões (Química)](work/cineticaRP.html){target="_blank"}

### [Painel - dashboard (C. da Natureza)](work/painel.html){target="_blank"}

### [Espirógrafo (Arte e Matemática)](work/espirogr.html){target="_blank"}

### [Jogo da Vida de Conway (Biologia)](work/lifesgame.html){target="_blank"}

### [Histograma (Estatística)](work/anim_histogr.html){target="_blank"}

### [Potencial de ação neuronal (Biologia)](work/anim_neuronio.html){target="_blank"}

### [Movimento circular (Física)](work/plan4_miniSistSol.html){target="_blank"}

### [Mini Sistema Sola2 - dados aproximados (Física)](work/miniSistSol.html){target="_blank"}

### [Afélio e Periélio (Física)](work/afelio_perielio.html){target="_blank"}

### [Oscilação harmônica (Física)](work/massa_mola.html){target="_blank"}

### [Movimento pendular (Física)](work/pendulo.html){target="_blank"}



## Áudio

### [Flauta doce (script)](work/flauta.js){target="_blank"}

### [Piano (script)](work/piano.js){target="_blank"}

## Multimídia interativa

### [Animação e interatividade - Jogo de Arco e Flecha](work/arcoFlecha.html){target="_blank"}

### [Animação, interatividade, e áudio - Jogo Pong](work/pong6.html){target="_blank"}









