---
title: "AIC - Critério de Informação de Akaike"
format: html
toc: true
toc-depth: 3
number-sections: true
lang: pt
---

|   O programa permite calcular parâmetros do *Critério de Informação de Akaike* para a distinção estatística de modelos não lineares.  
\

## Equação:


$$
AIC=n*ln(\frac{SSE}{n})+2k+[\frac{2k(k+1)}{n-k-1}]
$$
*Onde:*

* *k* = p + 1 (com *p* sendo o número de parâmetros);
* *SSE* = soma dos quadrados dos resíduos do ajuste
\


$$
probab.B = \frac{e^{-0.5* \Delta AIC}}{1+e^{-0.5* \Delta AIC}}
$$
\

*Onde:* 

* *probab. B* = probabilidade do modelo B ser melhor que o modelo A (0 a 1);
* *$\Delta$AIC* = diferença de AIC$_B$-AIC$_A$
\

## Arquivos:

1. [Programa AIC](/hp50g/AIC/AIC.zip)
2. [Código](/hp50g/AIC/AIC.pdf)
\

## Uso:

|   Para seu uso, o programa requer a entrada dos seguintes dados na sequência da pilha: 
\

```{r, eval=FALSE}

# Entrada de dados

1. n, kA, kB, SSE_A, SSE_B
```



## Exemplo

|   A tabela abaixo refere-se aos dados de inibição enzimática obtidos por Bezerra e cols (2013).
\

*Tabela 1*

| Tipo | Controle | Competitivo | Não compet. puro | Não compet. misto | Incompet. |
|------|----------|-------------|------------------|-------------------|-----------|
| SSE  | 1540.1   | 613.1       | 1122.7           | 613.2             | 1436.4    |
| p    | 2        | 3           | 3                | 4                 | 3         |



|   Procedendo-se a execução de *AIC*, foram obtidos os seguintes resultados de comparação para alguns pares de modelos:
\
*Tabela 2 — Resultados da comparação de modelos pelo critério AI.C*

| Modelo A / B            | AIC$_A$ | AIC$_B$ | $\Delta$ | Probab. B |
|-------------------------|---------|---------|----------|-----------|
| Controle / Competitivo  | 288.2   | 193.7   | -94.6    | 1.0       |
| Controle / NComp. misto | 288.2   | 195.9   | -92.3    | 1.0       |
| Compet. / NComp. misto  | 193.7   | 195.9   | 2.2      | 0.25      |


|   Pelos dados da tabela, a probabilidade do modelo B estar correto sugere a seleção do modelo competitivo de inibição enzimática (75% de chances sobre o modelo não competitivo misto). 

## Referências {.unnumbered}

1. Akaike, Hirotugu. "A new look at the statistical model identification." IEEE transactions on automatic control 19.6 (2003): 716-723.

2. Bezerra, Rui MF, Irene Fraga, and Albino A. Dias. "Utilization of integrated Michaelis–Menten equations for enzyme inhibition diagnosis and determination of kinetic constants using Solver supplement of Microsoft Office Excel." Computer methods and programs in biomedicine 109.1 (2013): 26-31.